# All the default ArchUp aliases and functions
# (don't mess with these directly, just override them here!)
source ~/.local/share/archup/default/bash/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
