// Code generated by MockGen. DO NOT EDIT.
// Source: internal/phases/phase.go
//
// Generated by this command:
//
//	mockgen -source=internal/phases/phase.go -destination=internal/phases/mocks/mock_phase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	phases "github.com/bnema/archup/internal/phases"
	gomock "go.uber.org/mock/gomock"
)

// MockPhase is a mock of Phase interface.
type MockPhase struct {
	ctrl     *gomock.Controller
	recorder *MockPhaseMockRecorder
	isgomock struct{}
}

// MockPhaseMockRecorder is the mock recorder for MockPhase.
type MockPhaseMockRecorder struct {
	mock *MockPhase
}

// NewMockPhase creates a new mock instance.
func NewMockPhase(ctrl *gomock.Controller) *MockPhase {
	mock := &MockPhase{ctrl: ctrl}
	mock.recorder = &MockPhaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhase) EXPECT() *MockPhaseMockRecorder {
	return m.recorder
}

// CanSkip mocks base method.
func (m *MockPhase) CanSkip() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanSkip")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanSkip indicates an expected call of CanSkip.
func (mr *MockPhaseMockRecorder) CanSkip() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSkip", reflect.TypeOf((*MockPhase)(nil).CanSkip))
}

// Description mocks base method.
func (m *MockPhase) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockPhaseMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockPhase)(nil).Description))
}

// Execute mocks base method.
func (m *MockPhase) Execute(progressChan chan<- phases.ProgressUpdate) phases.PhaseResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", progressChan)
	ret0, _ := ret[0].(phases.PhaseResult)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockPhaseMockRecorder) Execute(progressChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPhase)(nil).Execute), progressChan)
}

// Name mocks base method.
func (m *MockPhase) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPhaseMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPhase)(nil).Name))
}

// PostCheck mocks base method.
func (m *MockPhase) PostCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// PostCheck indicates an expected call of PostCheck.
func (mr *MockPhaseMockRecorder) PostCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostCheck", reflect.TypeOf((*MockPhase)(nil).PostCheck))
}

// PreCheck mocks base method.
func (m *MockPhase) PreCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// PreCheck indicates an expected call of PreCheck.
func (mr *MockPhaseMockRecorder) PreCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreCheck", reflect.TypeOf((*MockPhase)(nil).PreCheck))
}

// Rollback mocks base method.
func (m *MockPhase) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockPhaseMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockPhase)(nil).Rollback))
}

// SetStatus mocks base method.
func (m *MockPhase) SetStatus(status phases.PhaseStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockPhaseMockRecorder) SetStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockPhase)(nil).SetStatus), status)
}

// Status mocks base method.
func (m *MockPhase) Status() phases.PhaseStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(phases.PhaseStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockPhaseMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockPhase)(nil).Status))
}
